[COLNAMES_MAPPER]
mapper = {}

[TARGET_MEAN_ENCODE]
target_encode=false

[MACRO]
enrichment=true

[TRAIN_SAMPLE_PROPS]
train_sample_path = 'data/train_data.xlsx'
cumulative_days = 'Cumulative days of late payments'
target_days = 30
test_size = 0.15

[BLIND_SAMPLE_PROPS]
blind_path = 'data/blind_data.xlsx'

[FEATURES_PARAMS]
partner_name = 'FINCA Guatemala'
partners_country = 'UAE'
num_of_lags = 3
window = 7
date_col = 'Date of disbursement'