[COLNAMES_MAPPER]
mapper = {}

[TARGET_MEAN_ENCODE]
target_encode=true

[TRAIN_SAMPLE_PROPS]
train_sample_path = 'data/train_data.xlsx'
cumulative_days = 'Cumulative days of late payments'
test_size = 0.15

[BLIND_SAMPLE_PROPS]
blind_path = 'data/blind_data.xlsx'

[FEATURES_PARAMS]
partners_country = 'Guatemala'
num_of_lags = 3
window = 7
date_col = 'Date of disbursement'