[COLNAMES_MAPPER]
mapper = {}

[TARGET_MEAN_ENCODE]
target_encode=true

[TRAIN_SAMPLE_PROPS]
train_sample_path = 'data/loan_data_w_aecb.xlsx'
cumulative_days = 'cmltv_days'
target_days = 89
test_size = 0.15

[BLIND_SAMPLE_PROPS]
blind_path = 'data/blind_data.xlsx'

[FEATURES_PARAMS]
<<<<<<< Updated upstream
partner_name = 'FINCA Guatemala'
partners_country = 'Guatemala'
=======
partner_name = 'CBI'
partners_country = 'UAE'
>>>>>>> Stashed changes
num_of_lags = 3
window = 7
date_col = 'date_of_disbursement'