[SET_FEATURES]
model_params = {'learning_rate' = 0.1, 'depth' = 2, 'n_estimators' = 100, 'bootstrap_type' = 'Bernoulli', 'random_seed' = 10}

features_list = ['loan_amount', 'duration_at_disbursement_months', 'interest_rate', 'age', 'monthly_income_aed',
                  'work_experience', 'presence_of_car', 'collateral',
                  'employment_sphere', 'type_of_product', 'AECB Point In Time Score'
                  ]

cat_feature_list = ['employment_sphere', 'type_of_product']

type_ = 'baseline scoring model'
output_dir = 'data'

model_path = 'data/model_artifact'
sfa_dir = 'data/sfa_results'

[SFA_PARAMS]
model_params = {'iterations' = 500, 'learning_rate' = 0.2, 'depth' = 4}

[MODEL_PATH]
baseline_model = 'data/model_artifact/trained_model.pkl'

[THRESHOLD_REPORT]
min_thres = 5
max_thres = 20
stp_thres = 1