[SET_FEATURES]
model_params = { 'learning_rate' = 0.1, 'depth' = 2,'n_estimators' = 100,'bootstrap_type' = 'Bernoulli','random_seed' = 10}

features_list = [
    'loan_amount',
    'duration_at_disbursement_months',
    'interest_rate',
    'quantity_of_prior_loans_at_the_time_of_disbursement_at_cbi',
    'age',
    'monthly_income_aed',
    'quantity_of_prior_loans_at_cbi',
    'work_experience',
    'presence_of_car',
    'presence_of_housing',
    'dsr',
    'type_of_product',
    'location',
    'emirates',
    'gender',
    'family_status',
    'employment_sphere',
    'employment_level',
    'coborrower',
    'collateral']

cat_feature_list = [
	'type_of_product',
	'location','emirates','gender',
	'family_status',
   	'employment_sphere',
   	'employment_level',
   	'coborrower',
   	'collateral']

type_ = 'baseline scoring model'
output_dir = 'data'

model_path = 'data/model_artifact'
sfa_dir = 'data/sfa_results'

[TUNING]
use_tuning = true
tuning_params = { 'learning_rate' = [0.05,0.1], 'depth' = [1,5],'n_estimators' = [50,100],'bootstrap_type' = ['Bernoulli'],'random_seed' = 10,iterations=[1,2]}

[SFA_PARAMS]
model_params = {'iterations' = 500, 'learning_rate' = 0.2, 'depth' = 4}

[MODEL_PATH]
baseline_model = 'data/model_artifact/trained_model.pkl'

[THRESHOLD_REPORT]
min_thres = 5
max_thres = 20
stp_thres = 1