[METADATA]
author_name = 'Elon Musk'

[MLFLOW]
tracking_uri="http://13.81.254.179:5050"
experiment_name = 'cbi_scoring'

[SET_FEATURES]
model_params = {'iterations' = 10, 'random_seed' = 1}


features_list = [
       'Type of product', 'Branch', 'Location', 'Gender', 'Family status', 'Type of client (old / new)',
       'Education level', 'Employment sphere', 'Presence of housing', 'Co-borrower', 'Collateral', 'Loan amount',
       'Duration at disbursement (months)', 'Interest rate', 'Age', 'Monthly income', 'Quantity of prior loans', 'Quantity of dependents'
]

cat_feature_list = [
       'Type of product', 'Branch', 'Location', 'Gender', 'Family status', 'Type of client (old / new)', 'Education level',
       'Employment sphere', 'Presence of housing', 'Co-borrower', 'Collateral'
]

type_ = 'baseline scoring model'
output_dir = 'data'

model_path = 'data/model_artifact'
sfa_dir = 'data/sfa_results'

[TUNING]
use_tuning = false
tuning_params = {'learning_rate' = [0.03, 0.1], 'depth' = [1, 7], 'n_estimators' = [40, 150], l2_leaf_reg=[50, 200], subsample = [0, 1], 'random_seed' = [10]}

[SFA_PARAMS]
model_params = {'iterations' = 500, 'learning_rate' = 0.2, 'depth' = 4}

[MODEL_PATH]
baseline_model = 'data/model_artifact/trained_model.pkl'

[THRESHOLD_REPORT]
min_thres = 5
max_thres = 20
stp_thres = 1
