[SET_FEATURES]
model_params = {'iterations' = 5000, 'learning_rate' = 0.015, 'depth' = 5, 'loss_function' = 'Logloss', 'eval_metric' = 'AUC', 'random_seed' = 123}
features_list = ['balance', 'term', 'interest_rate', 'product', 'status_of_loan',
       'branchname', 'gender', 'customer_age', 'marital_status', 'salary',
       'education_level', 'no_of_dependents', 'employment_sphere',
       'employment_level', 'work_experience', 'is_car_asset', 'is_real_asset',
       'co_borrower', 'collateral']
cat_feature_list = ['product', 'status_of_loan', 'branchname', 'gender', 'marital_status',
       'education_level', 'employment_sphere', 'employment_level',
       'is_car_asset', 'is_real_asset', 'co_borrower', 'collateral']
type_ = 'baseline'
output_dir = 'data'
model_path = 'data/model_artefact'

[MODEL_PATH]
baseline_model = '/home/beck/projects/work_projects/scoring_pipeline/data/run_2023-10-31_11-58-57/model_artifact/baseline.pkl'