[SET_FEATURES]
model_params = {
       'iterations' = 500, 
       'random_seed' = 1
}
features_list = [
       'Type of product', 'Branch', 'Location', 'Gender', 'Family status', 'Type of client (old / new)', 'Education level', 
       'Employment sphere', 'Presence of housing', 'Co-borrower', 'Collateral', 'Loan amount', 'Duration at disbursement (months)', 
       'Interest rate', 'Age', 'Monthly income', 'Quantity of prior loans', 'Quantity of dependents'
]      
cat_feature_list = [
       'Type of product', 'Branch', 'Location', 'Gender', 'Family status', 'Type of client (old / new)', 'Education level', 
       'Employment sphere', 'Presence of housing', 'Co-borrower', 'Collateral'
]
type_ = 'adversarial validation'
output_dir = 'data'
model_path = 'data/model_artefact'

[MODEL_PATH]
baseline_model = '/model_artifact/adv_val.pkl'